spring.application.name=api-gateway
server.port=8765

eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka

#spring.cloud.gateway.discovery.locator.enabled=true
#spring.cloud.gateway.discovery.locator.lowerCaseServiceId=true

#spring.sleuth.sampler.probability=1.0
management.tracing.sampling.probability=1.0
logging.pattern.level=%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]

management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always

#management.tracing.export.zipkin.endpoint=http://localhost:9411/api/v2/spans
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always

management.tracing.export.enabled=true
management.opentelemetry.tracing.export.otlp.endpoint=http://localhost:4318/v1/traces